_target_: src.models.AdaHAT

s_max: 400.0
adjust_rate: 1e-06
reg:
  _target_: src.models.regs.MaskSparseReg
  factor: 0.1

log_train_mask: False

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

backbone:
  _target_: src.models.backbones.MaskedResNet18
  input_channels: 3

heads:
  _target_: src.models.heads.HeadsTIL
  input_dim: 512
